### ISSUE TITLE
No TTL set on entity keys

### ISSUE THREAD

**Issue by bencrouse** [redis-store/redis-rack-cache#3]
Our Redis instance filled up with keys because there's no TTL set on the entity keys. I see that Rack::Cache doesn't provide TTL to the MetaStore#write method, but I'm wondering if there's a suggested workaround or fix that could be done to prevent an unbounded number of keys. I'd be willing to do the work if there's an acceptable solution.

**Comment by mezis** [comment]
+1
Seeing this as an issue as well.

**Comment by radar** [comment]
@mezis Has this now been fixed by redis-store/redis-store#209?

**Comment by mezis** [comment]
@radar it has indeed. Sorry I didn't ping back to this issue!

**Comment by mezis** [comment]
Well, to be specific, when `use_native_ttl` is set _and_  using `redis-store` >= 1.1.5, the entity store no longer eventually overflows.

The metastore still doesn't support native TTLs.

**Comment by bencrouse** [comment]
we were experiencing the problem with the metastore keys.

**Comment by radar** [comment]
Ok. Is another patch needed here?

**Comment by mezis** [comment]
@radar there would, but the issue has to be solved in `Rack::Cache` itself first. At the moment `use_native_ttl` isn't honoured by the metastore.

rtomayko/rack-cache#92 has a proposed fix but it's been open for a long while.

**Comment by tubbo** [comment]
Fixed by #4 and #5.
